language: node_js

env:
  - CXX=g++-4.8

node_js:
  - iojs-2
  - iojs-3
  - 4
  - 5
  - 6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false

before_install:
  - $CXX --version
